2022-02-17 16:06:40,324 INFO    MainThread:84872 [wandb_setup.py:_flush():71] setting env: {}
2022-02-17 16:06:40,324 INFO    MainThread:84872 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-17 16:06:40,324 INFO    MainThread:84872 [wandb_init.py:_log_setup():371] Logging user logs to /home/soroosh/Programmes/DD/DD_package/wandb/run-20220217_160640-23meiwpn/logs/debug.log
2022-02-17 16:06:40,324 INFO    MainThread:84872 [wandb_init.py:_log_setup():372] Logging internal logs to /home/soroosh/Programmes/DD/DD_package/wandb/run-20220217_160640-23meiwpn/logs/debug-internal.log
2022-02-17 16:06:40,324 INFO    MainThread:84872 [wandb_init.py:init():404] calling init triggers
2022-02-17 16:06:40,324 INFO    MainThread:84872 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'fit_intercept': True}
2022-02-17 16:06:40,324 INFO    MainThread:84872 [wandb_init.py:init():460] starting backend
2022-02-17 16:06:40,324 INFO    MainThread:84872 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-17 16:06:40,325 INFO    MainThread:84872 [backend.py:ensure_launched():216] starting backend process...
2022-02-17 16:06:40,328 INFO    MainThread:84872 [backend.py:ensure_launched():221] started backend process with pid: 84913
2022-02-17 16:06:40,329 INFO    MainThread:84872 [wandb_init.py:init():469] backend started and connected
2022-02-17 16:06:40,331 INFO    MainThread:84872 [wandb_init.py:init():533] updated telemetry
2022-02-17 16:06:40,339 INFO    MainThread:84872 [wandb_init.py:init():563] communicating current version
2022-02-17 16:06:40,896 INFO    MainThread:84872 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-17 16:06:40,896 INFO    MainThread:84872 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-17 16:06:41,144 INFO    MainThread:84872 [wandb_init.py:init():606] starting run threads in backend
2022-02-17 16:06:42,001 INFO    MainThread:84872 [wandb_run.py:_console_start():1810] atexit reg
2022-02-17 16:06:42,001 INFO    MainThread:84872 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-02-17 16:06:42,001 INFO    MainThread:84872 [wandb_run.py:_redirect():1689] Redirecting console.
2022-02-17 16:06:42,002 INFO    MainThread:84872 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-17 16:06:42,002 INFO    MainThread:84872 [wandb_init.py:init():633] run started, returning control to user process
2022-02-17 16:06:42,116 ERROR   MainThread:84872 [util.py:get_module():187] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/util.py", line 182, in get_module
    return import_module(name)
  File "/home/soroosh/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plotly'
2022-02-17 16:06:42,516 INFO    MainThread:84872 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-02-17 16:06:42,517 INFO    MainThread:84872 [wandb_run.py:_restore():1752] restore
2022-02-17 16:06:47,560 ERROR   MainThread:84872 [wandb_run.py:_atexit_cleanup():1798] Problem finishing run
Traceback (most recent call last):
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1934, in _on_finish
    self.history._flush()
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1017, in _history_callback
    self._backend.interface.publish_history(
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 496, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/data_types.py", line 2597, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/data_types.py", line 2622, in val_to_json
    val = Plotly.make_plot_media(val)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/sdk/data_types.py", line 2547, in make_plot_media
    val = util.matplotlib_to_plotly(val)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/util.py", line 506, in matplotlib_to_plotly
    tools = get_module(
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/wandb/util.py", line 189, in get_module
    raise wandb.Error(required)
wandb.errors.Error: plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`
