2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_setup.py:_flush():75] Loading settings from /home/soroosh/.config/wandb/settings
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_setup.py:_flush():75] Loading settings from /home/soroosh/Programmes/DD/DD_package/wandb/settings
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'DD_package/main.py', 'program': '/home/soroosh/Programmes/DD/DD_package/main.py'}
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_init.py:_log_setup():386] Logging user logs to /home/soroosh/Programmes/DD/DD_package/wandb/run-20220225_144710-16vq65r8/logs/debug.log
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_init.py:_log_setup():387] Logging internal logs to /home/soroosh/Programmes/DD/DD_package/wandb/run-20220225_144710-16vq65r8/logs/debug-internal.log
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_init.py:init():420] calling init triggers
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {'alpha': 0.9958049784371157}
2022-02-25 14:47:10,075 INFO    MainThread:47066 [wandb_init.py:init():471] starting backend
2022-02-25 14:47:10,075 INFO    MainThread:47066 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-25 14:47:10,083 INFO    MainThread:47066 [backend.py:ensure_launched():219] starting backend process...
2022-02-25 14:47:10,089 INFO    MainThread:47066 [backend.py:ensure_launched():224] started backend process with pid: 47089
2022-02-25 14:47:10,090 INFO    MainThread:47066 [wandb_init.py:init():480] backend started and connected
2022-02-25 14:47:10,093 INFO    MainThread:47066 [wandb_init.py:init():550] updated telemetry
2022-02-25 14:47:10,110 INFO    MainThread:47066 [wandb_init.py:init():581] communicating current version
2022-02-25 14:47:10,930 INFO    MainThread:47066 [wandb_init.py:init():586] got version response 
2022-02-25 14:47:10,930 INFO    MainThread:47066 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-25 14:47:15,553 ERROR   Thread-1  :47066 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 14:47:15,553 ERROR   Thread-1  :47066 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 14:47:15,554 ERROR   Thread-1  :47066 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 146, in execute
    six.reraise(*sys.exc_info())
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-02-25 14:47:20,619 ERROR   Thread-1  :47066 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 14:47:20,620 ERROR   Thread-1  :47066 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 14:47:34,096 ERROR   Thread-1  :47066 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 14:47:34,096 ERROR   Thread-1  :47066 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 14:47:40,930 INFO    MainThread:47066 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-02-25 14:47:40,930 ERROR   MainThread:47066 [wandb_init.py:init():601] backend process timed out
2022-02-25 14:47:40,930 ERROR   MainThread:47066 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-02-25 14:50:17,754 INFO    MainThread:47066 [wandb_init.py:teardown():234] tearing down wandb.init
