Traceback (most recent call last):
  File "/home/soroosh/Programmes/DD/DD_package/main.py", line 401, in <module>
    cls_est.train_test_tuned_estimator()
  File "/home/soroosh/Programmes/DD/DD_package/dd_package/models/classification_estimators.py", line 380, in train_test_tuned_estimator
    y_pred_prob = self.estimator.predict_proba(v["x_test"])
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py", line 666, in predict_proba
    self._check_proba()
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py", line 633, in _check_proba
    raise AttributeError("predict_proba is not available when "
AttributeError: predict_proba is not available when  probability=False